import { readFileSync } from "node:fs";

/**
 * The workflow document, the marks every generated file carries, and the way
 * the rest of this directory reaches the prose written beside it.
 */

export const GENERATED =
  "<!-- Generated by @canon/cli. Run canon-cli init --force to replace. -->";

/**
 * Where the workflow itself is written. Every generated skill and reviewer
 * names this file instead of carrying a copy of it, so that the stages are
 * stated once and a project that edits them edits one file.
 */
export const WORKFLOW_PATH = ".canon/workflow.md";

/**
 * A document written beside this module, read as it was written. Markdown is
 * kept as Markdown so that the source of a generated file looks like the
 * file, and `npm run build` copies it next to the compiled modules.
 */
export function prose(name: string): string {
  return readFileSync(new URL(name, import.meta.url), "utf8").trimEnd();
}

export const WORKFLOW = `${GENERATED}\n${prose("./workflow.md")}\n`;

/**
 * What every generated file says in place of a copy of the workflow. It stays
 * beside the path it names: the two are one statement made twice.
 */
export const PREAMBLE = `Read \`${WORKFLOW_PATH}\` before acting: it holds the stages, their
separation and what decides that a set is valid, and it is normative here.`;
